name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@master
        with:
          USERNAME: preetham1869
          SHOW_ICONS: true
          INCLUDE_ALL_COMMITS: true
          COUNT_PRIVATE: false
          BG_COLOR: 050505
          TITLE_COLOR: F5F5F5
          TEXT_COLOR: D6D9DC
          ICON_COLOR: F5F5F5
          HIDE_BORDER: true
